let stock = [
    {id: 1, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 1200, img: './img/card1.jpg'},
    {id: 2, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 1100, img: './img/card1.jpg'},
    {id: 3, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamamangado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 1200, img: './img/card1.jpg'},
    {id: 4, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 1400, img: './img/card1.jpg'},
    {id: 5, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 1400, img: './img/card1.jpg'},
    {id: 6, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive sonsu familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 1500, img: './img/card1.jpg'},
    {id: 7, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 500, img: './img/card1.jpg'},
    {id: 8, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 500, img: './img/card1.jpg'},
    {id: 9, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 500, img: './img/card1.jpg'},
    {id: 10, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 700, img: './img/card1.jpg'},
    {id: 11, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1,descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 700, img: './img/card1.jpg'},
    {id: 12, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcionripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 700, img: './img/card1.jpg'},
    {id: 13, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 900, img: './img/card1.jpg'},
    {id: 14, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 1400, img: './img/card1.jpg'},
    {id: 15, nombre: "Demon Slayer 00", tipo: "manga", cantidad: 1, descripcion: "Kamado Tanjiro, un chico joven y bastante inteligente. Este vive son su familia y gana dinero vendiendo carbón. Pero todo cambia cuando su familia es atacada y asesinada.", precio: 7000, img: './img/card1.jpg'},
    
]